notifications:
  email: false
language: go
go:
  - "1.1"
  - "1.2"
install:
  - "sudo apt-get install lzop"
  - "wget https://github.com/coreos/etcd/releases/download/v0.4.4/etcd-v0.4.4-linux-amd64.tar.gz"
  - "tar -zxvf etcd-v0.4.4-linux-amd64.tar.gz"
  - "etcd-v0.4.4-linux-amd64/etcd -name travis &"
cache: apt
script: make test
